CREATE OR REPLACE PROCEDURE REMOVE_HS (
   P_ID    IN     JSHARDA.PATIENT.PID%TYPE,
   HS_ID   IN     JSHARDA.HEALTH_SUPPORTER.HSID%TYPE,
   RET        OUT INT)
IS
   SUPP_TYPE          CHAR (1);
   PATIENT_CATEGORY   CHAR (1);
--
-- Declare program variables as shown below
-- variable_name data_type
BEGIN
   SELECT SUPPORTER_TYPE
     INTO SUPP_TYPE
     FROM JSHARDA.HEALTH_SUPPORTER
    WHERE     HSID = HS_ID
          AND PATIENT_PID = P_ID
          AND (ENDDATE > CURRENT_TIMESTAMP OR ENDDATE IS NULL);

   SELECT CATEGORY
     INTO PATIENT_CATEGORY
     FROM JSHARDA.PATIENT
    WHERE PID = P_ID;


   IF (SUPP_TYPE = '')
   THEN
      RET := -1;
   ELSIF (SUPP_TYPE = 'S')
   THEN
      UPDATE JSHARDA.HEALTH_SUPPORTER
         SET ENDDATE = CURRENT_TIMESTAMP
       WHERE     HSID = HS_ID
             AND PATIENT_PID = P_ID
             AND (ENDDATE > CURRENT_TIMESTAMP OR ENDDATE IS NULL);

      RET := 1;
   ELSIF (SUPP_TYPE = 'P' AND GET_HS_COUNT (P_ID) = 1)
   THEN
      IF (PATIENT_CATEGORY = 'W')
      THEN -- SINCE PATIENT IS WELL, HE CAN REOMVE HIS ONLY PRIMARY HEALTH SUPPORTER TOO...
         UPDATE JSHARDA.HEALTH_SUPPORTER
            SET ENDDATE = CURRENT_TIMESTAMP
          WHERE     HSID = HS_ID
                AND PATIENT_PID = P_ID
                AND (ENDDATE > CURRENT_TIMESTAMP OR ENDDATE IS NULL);

         RET := 1;
      ELSE
         RET := -2;
      END IF;
   ELSIF (SUPP_TYPE = 'P' AND GET_HS_COUNT (P_ID) = 2)
   THEN
      UPDATE JSHARDA.HEALTH_SUPPORTER
         SET ENDDATE = CURRENT_TIMESTAMP
       WHERE     HSID = HS_ID
             AND PATIENT_PID = P_ID
             AND (ENDDATE > CURRENT_TIMESTAMP OR ENDDATE IS NULL);

      UPDATE JSHARDA.HEALTH_SUPPORTER
         SET SUPPORTER_TYPE = 'P'
       WHERE     PATIENT_PID = P_ID
             AND (ENDDATE > CURRENT_TIMESTAMP OR ENDDATE IS NULL)
             AND SUPPORTER_TYPE = 'S';

      RET := 1;
   END IF;
EXCEPTION
   WHEN NO_DATA_FOUND
   THEN
      RET := -1;
END;

--Procedure
/
